apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-event-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-event-app
  template:
    metadata:
      labels:
        app: student-event-app
    spec:
      containers:
      - name: student-event-app
        image: kushmithaa/student-event-app:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: student-event-service
spec:
  type: NodePort
  selector:
    app: student-event-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30011
